version: "3.7"
services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -e development -b '0.0.0.0'
    tty: true
    stdin_open: true
    volumes:
      - .:/rails-app
    ports:
      - "3000:3000"